/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIdRouteImport } from './routes/editor.$id'

const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importar': typeof ImportarRoute
  '/novo': typeof NovoRoute
  '/editor/$id': typeof EditorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importar': typeof ImportarRoute
  '/novo': typeof NovoRoute
  '/editor/$id': typeof EditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importar': typeof ImportarRoute
  '/novo': typeof NovoRoute
  '/editor/$id': typeof EditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/biblioteca'
    | '/configuracoes'
    | '/importar'
    | '/novo'
    | '/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/biblioteca'
    | '/configuracoes'
    | '/importar'
    | '/novo'
    | '/editor/$id'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/biblioteca'
    | '/configuracoes'
    | '/importar'
    | '/novo'
    | '/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ImportarRoute: typeof ImportarRoute
  NovoRoute: typeof NovoRoute
  EditorIdRoute: typeof EditorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  BibliotecaRoute: BibliotecaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ImportarRoute: ImportarRoute,
  NovoRoute: NovoRoute,
  EditorIdRoute: EditorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
